version: "3.7"
services:
  backend:
    container_name: wop-backend
    image: coffeemakingtoaster/wop-backend
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    
  mongo:
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: "none"

  
             
