name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
    # install/cache npm dependencies
      - name: cache packages
        run: npm i
        
     #  Start MongoDB 
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '5.0'
        
    # run unit tests    
      - name: unit tests
        run: npm run test:e2e
        
    # build     
      - name: build
        run: npm run build
        
    # save build as artifact
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist with env vars
          path: |
            dist
            dev.env
