name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    # merged...this should be changed if unit tests are implemented
      - name: cache and build
        run: |
          npm i
          npm run build
      # save build as artifact
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist with env vars
          path: |
            dist
            dev.env
